"""Django migration to add new fields to the Car model."""
# Generated by Django 5.2.2 on 2025-06-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add description, mileage, and pictures fields to the Car model."""

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of the car"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(default=0, help_text="Mileage in miles"),
        ),
        migrations.AddField(
            model_name="car",
            name="pictures",
            field=models.ImageField(blank=True, null=True, upload_to="car_images/"),
        ),
    ]
